# Request to login
POST http://localhost/toDoList/api/login.php
Content-Type: application/json

{
    "username": "jade",
    "password": "123"
}

###
# Request to check token
POST http://localhost/toDoList/api/check-token.php
Content-Type: application/json

{
    "token": "eJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg3NTk5MzIsImV4cCI6MTcxODc2MzUzMn0.uVUCItB3ZEhECLPh_KUQo3gz6lspsho3k4-ro0GSEvY"
}

###
# Request to student-add
POST http://localhost/toDoList/api/admin/student.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg3NjU2ODcsImV4cCI6MTcxODc2OTI4N30.4dO6QNJDmB4hjV06bDQqRYSvWx7BARQlZU-hxH_i94k"
}


###
# Request to student-add
POST http://localhost/toDoList/api/admin/student-add.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg3NjU2ODcsImV4cCI6MTcxODc2OTI4N30.4dO6QNJDmB4hjV06bDQqRYSvWx7BARQlZU-hxH_i94k",
    "username": "tototaob",
    "password": "tototaob"
}

###
# Change student password
POST http://localhost/toDoList/api/admin/student-change.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg3NjU2ODcsImV4cCI6MTcxODc2OTI4N30.4dO6QNJDmB4hjV06bDQqRYSvWx7BARQlZU-hxH_i94k",
    "new_pass": "ja",
    "c_new_pass": "ja",
    "admin_pass": "123",
    "user_id": "35"
}

###
# Edit student name
POST http://localhost/toDoList/api/admin/student-edit.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg3NjU2ODcsImV4cCI6MTcxODc2OTI4N30.4dO6QNJDmB4hjV06bDQqRYSvWx7BARQlZU-hxH_i94k",
    "username": "ja",
    "user_id": "35"
}

###
# teacher-add

POST http://localhost/toDoList/api/admin/teacher-add.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg1NzYwNjQsImV4cCI6MTcxODU3OTY2NH0.UZVEHtGTpM4zQcOHttmCOshALBm7THtVGhIftbTKcNE",
    "username": "teacher",
    "password": "teacher"
}

###
# teacher-change

POST http://localhost/toDoList/api/admin/teacher-change.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg1NzYwNjQsImV4cCI6MTcxODU3OTY2NH0.UZVEHtGTpM4zQcOHttmCOshALBm7THtVGhIftbTKcNE",
    "new_pass": "teacher",
    "c_new_pass": "teacher",
    "admin_pass": "123",
    "user_id": "34"
}

###
# teacher-edit
POST http://localhost/toDoList/api/admin/teacher-edit.php
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE4LCJyb2xlIjoxLCJpYXQiOjE3MTg1NzYwNjQsImV4cCI6MTcxODU3OTY2NH0.UZVEHtGTpM4zQcOHttmCOshALBm7THtVGhIftbTKcNE",
    "username": "teacher1",
    "user_id": "34"
}
